global without sharing class Constants {
    // Account
    public static final String ACCOUNT_TYPE_PROSPECT = 'Prospect';

    // Task
    public static final String TASK_STATUS_OVERDUE = 'Overdue';
    public static final String TASK_STATUS_COMPLETED = 'Completed';

    // Reader_Book_Relationship__c
    public static final String READER_BOOK_RELATIONSHIP_STATUS_ACTIVE = 'Active';
    public static final String READER_BOOK_RELATIONSHIP_STATUS_COMPLETE = 'Complete';

    // Debug messages
    public static final String DEBUG_BELL_NOTIFICATION = 'Problem sending notification: ';
    public static final String DEBUG_EMAIL_NOTIFICATION = 'Problem sending email notification: ';

    // Toast messages
    public static final String ACTIVE_BRB_UPDATED_TO_COMPLETE = 'Active talons completed successfully.';

}