global without sharing class Constants {
    // Account
    public static final String ACCOUNT_TYPE_PROSPECT = 'Prospect';

    // Task
    public static final String TASK_STATUS_OVERDUE = 'Overdue';
    public static final String TASK_STATUS_COMPLETED = 'Completed';

    // Debug messages
    public static final String DEBUG_BELL_NOTIFICATION = 'Problem sending notification: ';
    public static final String DEBUG_EMAIL_NOTIFICATION = 'Problem sending email notification: ';

    // Reader Book Relationship
    public static final String READER_BOOK_REL_STATUS_ACTIVE = 'Active';
}